/**
 * Kerangka Python Model Code Generator (Pydantic v2 & dataclasses)
 * Specification Version: 0.1
 * Status: Draft
 * License: Apache-2.0
 */

import { FieldDefinition, KIRDocument } from "../types.js";

export class PythonCodegen {
  static generate(kir: KIRDocument): string {
    const lines: string[] = [
      "# Python Model Definitions generated by Kerangka from " + kir.app,
      "# Generated at: " + new Date().toISOString(),
      "",
      "from __future__ import annotations",
      "from decimal import Decimal",
      "from datetime import date, datetime",
      "from enum import Enum",
      "from typing import Optional, List, Any",
      "from pydantic import BaseModel, Field",
      ""
    ];

    // Enums
    for (const [entityName, entity] of Object.entries(kir.entities || {})) {
      for (const [fieldName, field] of Object.entries(entity.fields)) {
        if (field.type === "enum" && field.values && field.values.length > 0) {
          const enumName = `${entityName}${this.capitalize(fieldName)}`;
          lines.push(`class ${enumName}(str, Enum):`);
          for (const val of field.values) {
            lines.push(`    ${val.toUpperCase()} = "${val}"`);
          }
          lines.push("\n");
        }
      }
    }

    // Pydantic Models
    for (const [entityName, entity] of Object.entries(kir.entities || {})) {
      lines.push(`class ${entityName}(BaseModel):`);
      const keyField = entity.key || "id";
      if (!entity.fields[keyField] && !entity.embedded) {
        lines.push(`    ${this.toSnakeCase(keyField)}: Optional[str] = None`);
      }

      for (const [fieldName, field] of Object.entries(entity.fields)) {
        const pyName = this.toSnakeCase(fieldName);
        const pyType = this.mapFieldToPyType(entityName, fieldName, field);
        if (field.required && field.default === undefined) {
          lines.push(`    ${pyName}: ${pyType}`);
        } else if (field.default !== undefined) {
          const defVal = typeof field.default === "string" ? `"${field.default}"` : field.default;
          lines.push(`    ${pyName}: Optional[${pyType}] = ${defVal}`);
        } else {
          lines.push(`    ${pyName}: Optional[${pyType}] = None`);
        }
      }

      lines.push("\n");
    }

    return lines.join("\n");
  }

  private static mapFieldToPyType(entityName: string, fieldName: string, field: FieldDefinition): string {
    switch (field.type) {
      case "string":
      case "email":
        return "str";
      case "int":
      case "integer":
        return "int";
      case "float":
        return "float";
      case "decimal":
        return "Decimal";
      case "boolean":
      case "bool":
        return "bool";
      case "date":
        return "date";
      case "datetime":
        return "datetime";
      case "enum":
        return `${entityName}${this.capitalize(fieldName)}`;
      case "ref":
        return "str";
      case "list":
        if (field.element) {
          if (field.element.type === "ref" && field.element.target) {
            return `List[${field.element.target}]`;
          }
          return `List[${this.mapFieldToPyType(entityName, fieldName, field.element)}]`;
        }
        return "List[Any]";
      default:
        return "Any";
    }
  }

  private static toSnakeCase(str: string): string {
    return str.replace(/([a-z0-9])([A-Z])/g, "$1_$2").toLowerCase();
  }

  private static capitalize(str: string): string {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
