/**
 * Kerangka TypeScript Code Generator
 * Specification Version: 0.1
 * Status: Draft
 * License: Apache-2.0
 */

import { FieldDefinition, KIRDocument } from "../types.js";

export class TypeScriptCodegen {
  static generate(kir: KIRDocument): string {
    const lines: string[] = [
      "/**",
      ` * TypeScript Model Definitions generated by Kerangka from ${kir.app}`,
      ` * Generated at: ${new Date().toISOString()}`,
      " */",
      ""
    ];

    // Enums
    for (const [entityName, entity] of Object.entries(kir.entities || {})) {
      for (const [fieldName, field] of Object.entries(entity.fields)) {
        if (field.type === "enum" && field.values && field.values.length > 0) {
          const enumName = `${entityName}${this.capitalize(fieldName)}`;
          const unionValues = field.values.map(v => `"${v}"`).join(" | ");
          lines.push(`export type ${enumName} = ${unionValues};`);
        }
      }
    }
    lines.push("");

    // Entity interfaces
    for (const [entityName, entity] of Object.entries(kir.entities || {})) {
      lines.push(`export interface ${entityName} {`);
      const keyField = entity.key || "id";
      if (!entity.fields[keyField] && !entity.embedded) {
        lines.push(`  ${keyField}?: string;`);
      }

      for (const [fieldName, field] of Object.entries(entity.fields)) {
        const optional = field.required ? "" : "?";
        const tsType = this.mapFieldToTsType(entityName, fieldName, field);
        lines.push(`  ${fieldName}${optional}: ${tsType};`);
      }

      lines.push("}\n");

      // Create Request payload type
      if (!entity.embedded) {
        lines.push(`export interface Create${entityName}Payload {`);
        for (const [fieldName, field] of Object.entries(entity.fields)) {
          if (!field.compute) {
            const optional = (field.required && field.default === undefined && fieldName !== entity.key) ? "" : "?";
            const tsType = this.mapFieldToTsType(entityName, fieldName, field);
            lines.push(`  ${fieldName}${optional}: ${tsType};`);
          }
        }
        lines.push("}\n");
      }
    }

    return lines.join("\n");
  }

  private static mapFieldToTsType(entityName: string, fieldName: string, field: FieldDefinition): string {
    switch (field.type) {
      case "string":
      case "email":
      case "date":
      case "datetime":
      case "time":
        return "string";
      case "int":
      case "integer":
      case "float":
      case "decimal":
        return "number";
      case "boolean":
      case "bool":
        return "boolean";
      case "enum":
        return `${entityName}${this.capitalize(fieldName)}`;
      case "ref":
        return field.target ? `${field.target}["id"] | ${field.target}` : "string";
      case "list":
        if (field.element) {
          if (field.element.type === "ref" && field.element.target) {
            return `Array<${field.element.target}>`;
          }
          return `Array<${this.mapFieldToTsType(entityName, fieldName, field.element)}>`;
        }
        return "Array<unknown>";
      default:
        return "unknown";
    }
  }

  private static capitalize(str: string): string {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
