/**
 * Kerangka GraphQL SDL Projection Generator
 * Specification Version: 0.1
 * Status: Draft
 * License: Apache-2.0
 */

import { FieldDefinition, KIRDocument } from "../types.js";

export class GraphQLGenerator {
  static generate(kir: KIRDocument): string {
    const lines: string[] = [
      `# GraphQL Schema generated by Kerangka from ${kir.app}`,
      `# Generated at: ${new Date().toISOString()}`,
      "",
      "scalar Date",
      "scalar DateTime",
      "scalar Decimal",
      "scalar JSON",
      ""
    ];

    const queryFields: string[] = [];
    const mutationFields: string[] = [];
    const enumDefinitions: string[] = [];

    for (const [entityName, entity] of Object.entries(kir.entities || {})) {
      const typeFields: string[] = [];
      const createInputFields: string[] = [];
      const updateInputFields: string[] = [];
      const filterInputFields: string[] = [];

      for (const [fieldName, field] of Object.entries(entity.fields)) {
        // Enums
        let fieldGqlType = this.mapFieldToGqlType(field);
        if (field.type === "enum" && field.values && field.values.length > 0) {
          const enumName = `${entityName}${this.capitalize(fieldName)}Enum`;
          fieldGqlType = enumName;
          const enumValues = field.values.map(v => `  ${v.toUpperCase()}`).join("\n");
          enumDefinitions.push(`enum ${enumName} {\n${enumValues}\n}`);
        }

        const nullability = field.required ? "!" : "";
        typeFields.push(`  ${fieldName}: ${fieldGqlType}${nullability}`);

        // Exclude compute fields from create and update inputs
        if (!field.compute) {
          const createNullability = (field.required && field.default === undefined && fieldName !== entity.key) ? "!" : "";
          createInputFields.push(`  ${fieldName}: ${fieldGqlType}${createNullability}`);
          updateInputFields.push(`  ${fieldName}: ${fieldGqlType}`);
        }

        filterInputFields.push(`  ${fieldName}: ${fieldGqlType}`);
      }

      // Output main type
      lines.push(`type ${entityName} {`);
      lines.push(...typeFields);
      lines.push("}\n");

      if (!entity.embedded) {
        // Inputs
        lines.push(`input Create${entityName}Input {`);
        lines.push(...createInputFields);
        lines.push("}\n");

        lines.push(`input Update${entityName}Input {`);
        lines.push(...updateInputFields);
        lines.push("}\n");

        lines.push(`input ${entityName}FilterInput {`);
        lines.push(...filterInputFields);
        lines.push("}\n");

        // Queries
        queryFields.push(`  get${entityName}(id: ID!): ${entityName}`);
        queryFields.push(`  list${entityName}(filter: ${entityName}FilterInput, limit: Int, offset: Int): [${entityName}!]!`);

        // Mutations
        mutationFields.push(`  create${entityName}(input: Create${entityName}Input!): ${entityName}!`);
        mutationFields.push(`  update${entityName}(id: ID!, input: Update${entityName}Input!): ${entityName}!`);
        mutationFields.push(`  delete${entityName}(id: ID!): Boolean!`);

        // Workflow transitions
        if (entity.workflow?.transitions) {
          for (const actionName of Object.keys(entity.workflow.transitions)) {
            mutationFields.push(
              `  ${entityName.toLowerCase()}${this.capitalize(actionName)}(id: ID!): ${entityName}!`
            );
          }
        }

        // Custom actions
        if (entity.actions) {
          for (const [actionName, action] of Object.entries(entity.actions)) {
            let inputParam = "";
            if (action.input && Object.keys(action.input).length > 0) {
              const actionInputName = `${entityName}${this.capitalize(actionName)}Input`;
              const actionFields = Object.entries(action.input).map(([k, v]) => {
                const gqlType = this.mapFieldToGqlType(v);
                return `  ${k}: ${gqlType}${v.required ? "!" : ""}`;
              });
              lines.push(`input ${actionInputName} {`);
              lines.push(...actionFields);
              lines.push("}\n");
              inputParam = `, input: ${actionInputName}!`;
            }
            mutationFields.push(
              `  execute${entityName}${this.capitalize(actionName)}(id: ID!${inputParam}): ${entityName}!`
            );
          }
        }
      }
    }

    if (enumDefinitions.length > 0) {
      lines.unshift(...enumDefinitions, "");
    }

    if (queryFields.length > 0) {
      lines.push("type Query {");
      lines.push(...queryFields);
      lines.push("}\n");
    }

    if (mutationFields.length > 0) {
      lines.push("type Mutation {");
      lines.push(...mutationFields);
      lines.push("}\n");
    }

    return lines.join("\n");
  }

  private static mapFieldToGqlType(field: FieldDefinition): string {
    switch (field.type) {
      case "string":
      case "email":
        return "String";
      case "int":
      case "integer":
        return "Int";
      case "float":
        return "Float";
      case "decimal":
        return "Decimal";
      case "boolean":
      case "bool":
        return "Boolean";
      case "date":
        return "Date";
      case "datetime":
        return "DateTime";
      case "ref":
        return field.target || "ID";
      case "list":
        if (field.element) {
          const inner = this.mapFieldToGqlType(field.element);
          return `[${inner}!]`;
        }
        return "[JSON!]";
      default:
        return "String";
    }
  }

  private static capitalize(str: string): string {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1);
  }
}
